# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-19 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import utils.shortcuts


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_challenge_submission_python'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='id',
            field=models.TextField(db_index=True, default=utils.shortcuts.rand_str, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submission_python',
            name='id',
            field=models.TextField(db_index=True, default=utils.shortcuts.rand_str, primary_key=True, serialize=False),
        ),
    ]
