# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-19 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0008_auto_20190119_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='identifier',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='submission_python',
            name='id',
            field=models.TextField(default='', primary_key=True, serialize=False),
        ),
    ]
