# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-19 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0009_auto_20190119_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='identifier',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='id',
            field=models.TextField(default='', primary_key=True, serialize=False),
        ),
    ]
