# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-19 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0010_auto_20190119_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission_python',
            name='id',

            field=models.TextField(default='', primary_key=True, serialize=False),
        ),
    ]
