# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-19 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0016_auto_20190119_1331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Challenge',
        ),
        migrations.DeleteModel(
            name='Submission_python',
        ),
    ]
