# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-20 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0018_challenge_submission_python'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Challenge',
        ),
        migrations.DeleteModel(
            name='Submission_python',
        ),
    ]
